version: '2'

services:
    messenger:
        build: .
        image: alecholmez/messenger
        depends_on:
            - nats
        expose:
            - 8080
        ports:
            - "8080:8080"
        environment:
            - "NATS_URL=nats://nats:4222"
            - "MONGO_URL=mongo:27017"

    nats:
        image: nats:latest
        ports:
            - "8222:8222"
        expose:
            - 8222

    mongo:
        image: mongo:latest
